### Generates the bash script that is used to kickstart the program

"""
This file generates the BASH script that is used on the target PC. Given the package manager that is being used,
the script will update the system, download Git, Ansible, and GNU Stow and start the Ansible playbook generated.
"""

from datetime import datetime
import os

OUTPUT_FILENAME = "autorun.sh"


def generate_script(pm):
    """Configures a bash script to kickstart the auto configuration."""
    match pm:
        case "apt":
            install_cmd = "sudo apt-get update && sudo apt-get install -y"
        case "dnf":
            install_cmd = "sudo dnf upgrade && sudo dnf install -y"
        case "pacman":
            install_cmd = "sudo pacman -Sy && sudo pacman -S --noconfirm --needed"
        case "brew":
            install_cmd = "brew install"
        case _:
            raise ValueError("Package manager isn't supported")

    package_list = ["git", "ansible", "stow"]
    package_list_str = "\\\n    ".join(package_list)

    script_content = f"""#!/bin/bash
### Autogenerated execution script
### Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
### Detected package manager {pm}

echo "Running basic setup..."
{install_cmd} \\
    {package_list_str}
    
echo "Setup complete! Executing playbook."

ansible-playbook playbool.yml --ask-become-pass

echo "Playbook complete! Rebooting system!"

reboot now
"""

    with open(OUTPUT_FILENAME, "w") as f:
        f.write(script_content)

    os.chmod(OUTPUT_FILENAME, 0o755)
    return 0


def main():
    """Mainline function to generate the executable file"""

    pm = None

    # TODO: if I have a package manager that isn't supported i should print the error
    try:
        generate_script(pm)
    except:
        print("Package manager not detected or supported")


if __name__ == "__main__":
    main()
