### Generates the bash script that is used to kickstart the program

from datetime import datetime
import os

OUTPUT_FILENAME = "autorun.sh"


def generate_script(pm):
    """Configures a bash script to kickstart the auto configuration."""
    match pm:
        case "apt":
            install_cmd = "sudo apt-get update && sudo apt-get install -y"
        case "dnf":
            install_cmd = "sudo dnf upgrade && sudo dnf install -y"
        case "pacman":
            install_cmd = "sudo pacman -Sy && sudo pacman -S --noconfirm --needed"
        case "brew":
            install_cmd = "brew install"

    package_list = ["git", "ansible", "stow"]
    package_list_str = "\\\n    ".join(package_list)

    script_content = f"""#!/bin/bash
### Autogenerated execution script
### Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
### Detected package manager {pm}

echo "Running basic setup..."
{install_cmd} \\
    {package_list_str}
    
echo "Setup complete! Executing playbook."

ansible-playbook playbool.yml --ask-become-pass

echo "Playbook complete! Rebooting system!"

reboot now
"""

    with open(OUTPUT_FILENAME, "w") as f:
        f.write(script_content)

    os.chmod(OUTPUT_FILENAME, 0o755)
    return 0


def main():
    """Mainline function to generate the executable file"""

    # TODO: Package manager should get value from the calling script, not 'auto-detect it'
    pm = None

    if not pm:
        raise ValueError("Package manager not detected or not supported")

    generate_script(pm)


if __name__ == "__main__":
    main()

